import 'dart:io';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:animate_do/animate_do.dart';
import 'package:screenshot/screenshot.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:permission_handler/permission_handler.dart';
import '../utils/app_colors.dart';
import '../widgets/custom_button.dart';
import '../widgets/qr_display.dart';
import '../widgets/input_field.dart';
import '../utils/qr_saver.dart';

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final TextEditingController _controller = TextEditingController();
  final ScreenshotController _screenshotController = ScreenshotController();
  String _qrData = '';

  void _onGenerate() {
    setState(() {
      _qrData = _controller.text;
    });
    if (_qrData.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter some text or a link')),
      );
    }
  }

  Future<void> _shareQR() async {
    if (_qrData.isEmpty) return;
    
    final image = await _screenshotController.capture();
    if (image != null) {
      final xFile = XFile.fromData(image, mimeType: 'image/png', name: 'qr_code.png');
      await Share.shareXFiles([xFile], text: 'Check out my QR Code generated by QR Generator!');
    }
  }

  Future<void> _saveQR() async {
    if (_qrData.isEmpty) return;

    final image = await _screenshotController.capture();
    if (image == null) return;

    final fileName = 'QR_${DateTime.now().millisecondsSinceEpoch}.png';

    await saveQRCode(image, fileName, context);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [
              AppColors.backgroundStart,
              AppColors.backgroundMid,
              AppColors.backgroundEnd
            ],
          ),
        ),
        child: SafeArea(
          child: SingleChildScrollView(
            padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 40.0),
            child: Column(
              children: [
                FadeInDown(
                  child: Column(
                    children: [
                      const Icon(Icons.qr_code_2, size: 80, color: AppColors.primary),
                      const SizedBox(height: 16),
                      Text(
                        'QR Generator',
                        style: GoogleFonts.outfit(
                          color: AppColors.textPrimary,
                          fontSize: 32,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      Text(
                        'Convert any link or text to QR',
                        style: GoogleFonts.outfit(
                          color: AppColors.textSecondary,
                          fontSize: 16,
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 40),
                FadeInLeft(
                  child: InputField(
                    controller: _controller,
                    hintText: 'Paste link or type here...',
                    icon: Icons.link,
                  ),
                ),
                const SizedBox(height: 24),
                FadeInRight(
                  child: CustomButton(
                    text: 'Generate QR Code',
                    icon: Icons.auto_awesome,
                    onPressed: _onGenerate,
                    color: AppColors.primary,
                  ),
                ),
                const SizedBox(height: 40),
                if (_qrData.isNotEmpty) ...[
                  Screenshot(
                    controller: _screenshotController,
                    child: Container(
                      color: Colors.transparent, // Background for screenshot
                      child: QrDisplay(data: _qrData),
                    ),
                  ),
                  const SizedBox(height: 24),
                  Row(
                    children: [
                      Expanded(
                        child: FadeInUp(
                          child: OutlinedButton.icon(
                            onPressed: _saveQR,
                            icon: const Icon(Icons.download, color: Colors.white),
                            label: const Text('Save', style: TextStyle(color: Colors.white)),
                            style: OutlinedButton.styleFrom(
                              padding: const EdgeInsets.symmetric(vertical: 16),
                              side: const BorderSide(color: Colors.white24),
                              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: FadeInUp(
                          child: OutlinedButton.icon(
                            onPressed: _shareQR,
                            icon: const Icon(Icons.share, color: Colors.white),
                            label: const Text('Share', style: TextStyle(color: Colors.white)),
                            style: OutlinedButton.styleFrom(
                              padding: const EdgeInsets.symmetric(vertical: 16),
                              side: const BorderSide(color: Colors.white24),
                              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ],
            ),
          ),
        ),
      ),
    );
  }
}
